### ISSUE TITLE
Add trailing comma prettier formatting

### ISSUE THREAD

**Issue by nickscialli-usds** [usds/case-issue-navigator#8]
Prettier has a [config option](https://prettier.io/docs/en/options.html#trailing-commas) to use trailing commas where possible. We should

- Create a Prettier config file and add the trailing comma options
- Apply prettier to all files

**Comment by nickscialli-usds** [comment]
Planning on closing this issue unless there are any strong objections; the current trailing comma rules are working fine

**Comment by timothybest-usds** [comment]
I am fine with closing this. As long as we are consistent with a format I don’t have strong opinions on any specific linting policy

**Comment by nickscialli-usds** [comment]
I believe Ben finds diffs to be a bit cleaner when you always have a trailing comma, which I could see, but it doesn't bother me
